Manager: Use prebuilt toybox
bmax121/APatch pull request #641
Opened 2024-08-31 00:33 UTC by SakuraKyuo

* workarounds boot patch issue on some ROMs which using 4.x kernel

2024-08-31 00:36 UTC, marat2509 commented
Are there any test results of this solution on devices where the boot patch failed with the built-in toybox?

2024-08-31 00:47 UTC, SakuraKyuo commented
> Are there any test results of this solution on devices where the boot patch failed with the built-in toybox?

It has been tested on the devices which got boot patch failed, and the result is a successful patch. This commit mainly solves the problem that `grep` in the toybox of devices which using 4.x kernel cannot obtain the kernel configuration due to the lack of necessary argments and the patch script is forced to end.

2024-08-31 00:48 UTC, marat2509 approved these changes

2024-09-04 00:53 UTC, pomelohan requested changes
I don’t think introducing a full toybox for only 1 small feature is acceptable. We’d like to use C++ to write a small parser.

2024-11-04 14:28 UTC, closed without merging